### ISSUE TITLE
うなづき検知のところ、すごくエラー出てる

### ISSUE THREAD

**Issue by yhakamay** [hummingbird-jp/stat-web#117]
@RQ2L84Q-ROW これって想定内？うなづき検知も機能してなさそう？
![image](https://user-images.githubusercontent.com/65002858/132932880-5432b0d3-b01c-4199-bc13-f20d45e3a6c1.png)

**Comment by RQ2L84Q-ROW** [comment]
あんまり想定してる挙動ではないな
顔がちゃんと検知できてないときのエラー処理は未実装だから、それかも？

**Comment by RQ2L84Q-ROW** [comment]
わかった。script tag を`defer`にしたときに、Tensorflowが読み込まれる前にBlazeFaceのモデル読もうとしてるんだ
