### ISSUE TITLE
Book token (meeting info) for future meeting

### ISSUE THREAD

**Issue by RQ2L84Q-ROW** [hummingbird-jp/stat-web#139]
**Is your feature request related to a problem? Please describe.**
1. I would like to get meeting URL before the meeting, like ZOOM.
2. Then, I will share URL to those who may join.
3. The meeting begins when I (= host) join.

**Describe the solution you'd like**
Generate token string beforehand but do not create token itself before the host starts it.

**Additional context**
User authentication should be implemented before this feature.

**Comment by yhakamay** [comment]
これは確かに欲しいんだけど、パフォーマンスと相談かな 🤔 むしろアクセスしたタイミングで（＝ユーザー名入力してる間に）token & channelは生成するように変更しようかと思っていて、そうなるとこの変更が出来ないのよね 😢 良い折衷案が思いついたら是非とも実装したい

**Comment by RQ2L84Q-ROW** [comment]
I am closing this Issue since PR #195 resolved it! Thanks for the comments and suggestions!
