### ISSUE TITLE
Separate web pages based on their functions

### ISSUE THREAD

**Issue by RQ2L84Q-ROW** [hummingbird-jp/stat-web#142]
**Is your feature request related to a problem? Please describe.**
Currently everything in one page, but (thus) it takes long to load.

**Describe the solution you'd like**
Make Route, for example:
1. Start page (sign-in)
2. Create meeting token
3. Meeting page

**Describe alternatives you've considered**
One pager will do.

**Comment by yhakamay** [comment]
確かにロード時間長くなっちゃってるから、そろそろここは取り組まなければ… 複数の `html` を用意して、Node.jsで頑張ります

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay 別のhtmlを用意して試してみてるんだけど、Firestoreのルールにひっかかっちゃって、そこで止まってる。

`localhost:8080` でサインインしたあと、`localhost:8080/meeting/` に入ったときに認証情報が引き継げてないのが
原因だと思うんだけど、うまく解決できてない！

![Screen Shot 2021-09-17 at 15 27 19](https://user-images.githubusercontent.com/62736166/133734942-a46c066e-38e1-4479-a06b-95caee35fa65.png)

https://firebase.google.com/docs/auth/web/auth-state-persistence#web-v9
上のとかは試してみたんだけど、どうもうまくいかない

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay ページが遷移するとFirestoreの`read/write`ルール（`if request.auth != null`）に引っかかってしまう件、なんとかなったかも

```javascript
```

**Comment by RQ2L84Q-ROW** [comment]
ページをまたがる場合は、その都度、ユーザーのAuthenticationがちゃんとあるかどうかの確認が必要っぽい。

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW おおー、素晴らしい 👏  なるほどね、勉強になりました。 `onAuthStateChanged` は知ってたのにパッと思いつかなかった 😢
