### ISSUE TITLE
Integrate user information between Authentication and Agora

### ISSUE THREAD

**Issue by RQ2L84Q-ROW** [hummingbird-jp/stat-web#143]
**Is your feature request related to a problem? Please describe.**
User information such as `uid` and `userName` is not shared between Authentication, Firestore and Agora.

**Describe the solution you'd like**
1. `uid` : Use Authentication 🆔 
2. `userName` : Use input value 📛 

**Describe alternatives you've considered**
- `userName` : can be Authentication's display name instead.

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay 取り掛かり始めました！
ついでに、朝〜午前中のMergeで消えちゃってた？Welcome Messageはここで復元しておく！

```html
<!-- Welcome Message -->
<div id="welcome-message" class="toast" role="alert" aria-live="assertive" aria-atomic="true"
	style="z-index: 10000;">
	<div class="toast-header">
		<!--<img src="..." class="rounded me-2" alt="...">-->
		<strong id="display-name" class="me-auto">Welcome back 👋</strong>
		<!--<small>11 mins ago</small>-->
		<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
	</div>
	<div class="toast-body">
		We're so happy that you're back! Enjoy your time 🙃
	</div>
</div>
```

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW あー！ここで消えてたのか、すまぬ 🙇‍♂️ ありがとう！関係ないdiffを減らすために、 #141 でも復元するね

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay ありがと！このあとここのPR出せそうなんだけど、けっこうリファクタリングしてたりして大変になっちゃうかも
Firestoreの`root/users`コレクションにもユーザ情報を追加できるようになりそう 🎉 
![Screen Shot 2021-09-16 at 16 11 26](https://user-images.githubusercontent.com/62736166/133567378-6ea9cfdc-9736-4cf3-8850-39253733d810.png)
