### ISSUE TITLE
Meeting Info URL is too long

### ISSUE THREAD

**Issue by RQ2L84Q-ROW** [hummingbird-jp/stat-web#155]
**Is your feature request related to a problem? Please describe.**
Current URL is too long. It looks like below.
Let's make it short!
```
https://stat-web-6372a.web.app/?token=006adaa9fb7675e4ca19ca80a6762e44dd2IAD9zT911tdnzkZyj91Fp2Hrm2HdCR/LWgNYfL2UTyTWvsJMuSAAAAAAEAAWheKKr2ZEYQEAAQAAAAAA&channel=mTlQOr5ERfiNlqhBlsEl
```

**Describe the solution you'd like**
It is not easy to compress the string itself.
I think use map for token and channel name will do good.

1. Generate `token` and `channel`,  but don't activate them yet.
2. Add new document to Firestore 'token' collection (for example).
    - Use `firestore.addDoc()` to generate unique document id.
3. Use document id as hashed string for new URL.

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay 質問！
Agoraのトークンは24時間の有効期限付きだと思うんだけど、
Herokuで生成される token ってどのタイミングでAgoraに認知されるんだろう？

1. heroku内部で生成された時点でAgoraにも伝わっていて、その時点で24時間の期限はスタートしてる？
2. `index.js` で `join` した瞬間にAgora側で認知される？

後者なら、予めToken作っておいて保持しておけるかな？って思って。

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW 
> 1. heroku内部で生成された時点でAgoraにも伝わっていて、その時点で24時間の期限はスタートしてる？2. index.js で join した瞬間にAgora側で認知される？

1. が正しい！つまり、**Create時点から24時間に設定されてる**。なので、予め生成しておくには以下の実装が必要という認識 👇 
1. token & channelのハッシュみたいなものを別で持っておく
2. Shared linkにはtoken & channelの代わりにこのハッシュを含める
3. join時に、そのハッシュを元にしたtoken & channelを生成する

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay なるほどね〜ありがとう😊
短くするのはイメージついた気がする！

24時間より先の予約は
1. Tokenとchannelフィールドが空のドキュメントを作っておいて、そのdocument IdをURLに含める
2. そのURLではじめて参加したときに、token, channelを生成してドキュメントを更新する
3. 以降に参加する人はそのドキュメントにあるtokenと channel情報を使って参加


とか？
tokenとchannelの違いをもっと意識した方がいい気がしてきた

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay こんなフローで実装しようと思ってます！

![image](https://user-images.githubusercontent.com/62736166/133958776-6151b0d2-6020-4b78-bb8f-0392ef2f5caa.png)

![Screen Shot 2021-09-20 at 14 02 43](https://user-images.githubusercontent.com/62736166/133958789-a0db0922-4cb4-4abb-a748-a1ad047cea08.png)

**Comment by RQ2L84Q-ROW** [comment]
### 経過報告
新しくミーティングルームを作るときの動作イメージ（実際にFirestoreに新しくドキュメントを作ってる）

https://user-images.githubusercontent.com/62736166/133991348-13245d76-1a4c-4954-b71a-2417051b5f5b.mov

![image](https://user-images.githubusercontent.com/62736166/133991595-2f955b12-a421-4af0-8d69-9bba317b4ffb.png)

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW めちゃくちゃいいね！楽しみにしてる！手伝える所あれば教えて 👌

**Comment by RQ2L84Q-ROW** [comment]
チャンネル名を指定してCreateする場合の画面ができてきた！
まだCreateボタン以降は実装してない〜
https://user-images.githubusercontent.com/62736166/134275592-e9ed5f96-32f0-4e31-9b30-e80dac0a62da.mov

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW すげえ〜〜めちゃくちゃいけてるやん 🎉  20sあたりで細かいところ気になって、`Unsupported` なのに `Already taken` なのはどういうこと？笑

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay スペースが含まれたからだと思う！

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW あ、`Already taken` は一部一致で反応するのかな？`Unsupported` なら "taken" されてるはずがないのに、なんで共存するんだろう 🤔 と思ってしまった
