### ISSUE TITLE
Replace "Sign In with Google" with new Google Identity

### ISSUE THREAD

**Issue by yhakamay** [hummingbird-jp/stat-web#164]
**Is your feature request related to a problem? Please describe.**
Use new Google Identity: https://developers.google.com/identity. Legacy "Sign In with Google" is deprecated and will be stopped by 2023.

**Describe the solution you'd like**
This change may deliver users a completely continuous experience.

**Describe alternatives you've considered**
N/A.

**Additional context**
Google Identity needs a Privacy Policy and Terms of Service, which is done at #157.

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW 君のアカウント、もしかして古すぎる？？
![Uploading スクリーンショット 2021-09-18 14.50.07.png…]()

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay ほう？
たしかに、2011年とかに取得したアカウントではある笑笑

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW Verificationのために取得の理由を求められてて、こんな感じで良いですか？
```
Stat! is a Web RTC project which makes your meetings more productive and creative.

We're requesting two scopes: email address and public profile.

We use OAuth to deliver an utterly continuous experience: a) Users don't need a user account and password. b) User Name will be automatically set using Google User Display Name (note that users can change it anytime).
```

**Comment by RQ2L84Q-ROW** [comment]
良いと思う！ありがとう！

**Comment by yhakamay** [comment]
Waiting for a response from Google Trust & Safety Team...

**Comment by RQ2L84Q-ROW** [comment]
これができるようになると、今の`signInWithPopup`は使わなくなる？引き続き使える？

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW 使わなくなる！リダイレクトに切り替え＆一度サインインしたユーザーは自動的にサインインという流れになります

**Comment by RQ2L84Q-ROW** [comment]
StackOverflowで似たようなのがあったから参考になるかも
https://stackoverflow.com/questions/64357838/how-to-properly-configure-firebase-auth-in-a-single-page-application-spa

**Comment by yhakamay** [comment]
Verification、OAuth同意画面にロゴをアップロードしなければ必要なかったです… そして一度アップロードしたものを削除する手立てがなく、引き続きコミュニケーションを取るしかない 🤕  軽率にロゴをアップロードしてしまい誠に申し訳ございませんでした
https://stackoverflow.com/a/62467444/13676510
