### ISSUE TITLE
User name turns to uid after the user unpublished

### ISSUE THREAD

**Issue by yhakamay** [hummingbird-jp/stat-web#173]
**Describe the bug**

**To Reproduce**
1. Go to Stat!
2. Click on Create/Join
3. Ask other(s) to unpublish and publish again
4. See the error

**Expected behavior**
User names are always shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/65002858/133888515-910d5ac8-5607-4dc0-9db3-733635b269b7.png)

**Additional context**

**Comment by RQ2L84Q-ROW** [comment]
Note:
Update Firestore `/{metingId}/users` collection when `published/unpublished`
