### ISSUE TITLE
Stop video without muting myself

### ISSUE THREAD

**Issue by RQ2L84Q-ROW** [hummingbird-jp/stat-web#187]
**Is your feature request related to a problem? Please describe.**
I want to hide my video, but I want to talk.

**Describe the solution you'd like**
Stop streaming video but don't stop stream audio.
Also, I want a mute function.

**Comment by yhakamay** [comment]
I'm tackling this issue. 

- [ ] Add a "stop video" button
- [ ] Implement functionality for the button
