### ISSUE TITLE
Control with keypress works even when I typing channel name

### ISSUE THREAD

**Issue by RQ2L84Q-ROW** [hummingbird-jp/stat-web#196]
**Describe the bug**
When I type my channel name at `Create Your Room` or `Join Meeting`,
there appears a window telling me "Ghost, you are hiding ...".

I think it is because the event listener is created before the call starts.

**To Reproduce**
1. Click `Create Your Room`
2. Type something like `hummingbird`
3. The sign says I am at ghost mode
4. When I click `join`, I start with ghost mode, which is not expected!

**Expected behavior**
Event listeners of keypress controls should be set after the call began.

<img width="1440" alt="Screen Shot 2021-09-22 at 22 12 24" src="https://user-images.githubusercontent.com/62736166/134350069-8db92e2a-bfbf-4145-ba4f-a9b06432b7e1.png">

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW Thanks for your report. I'll work on this issue as most important.
