### ISSUE TITLE
ユーザー名の候補が分かりづらい

### ISSUE THREAD

**Issue by yhakamay** [hummingbird-jp/stat-web#75]
暫定処置としてプルダウンにします

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay  ユーザー名、Firestore連携の変更に伴って任意の名前で大丈夫になりそう！もし実装始めてたらごめん！

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW 別のアプローチで解決するみたいなので、クローズ
