### ISSUE TITLE
Limit meeting time

### ISSUE THREAD

**Issue by yhakamay** [hummingbird-jp/stat-web#81]
デモでいろんな人に配布すると思うんだけど、悪意を持って（なくても寝落ちとか）長時間使用されるとAgoraからの請求額が死んじゃう 👼

**Comment by yhakamay** [comment]
露出してるJSで扱うと書き換え放題だから、Cloud Functionsにお任せしようかな

1. Create → 新しい `meetingId` でドキュメントを生成する
2. `onCreate` で終了時間を返す

**Comment by RQ2L84Q-ROW** [comment]
NPMになったから、JSでできるようになった？
これ取り組んでよければやります！

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW 非常にありがたい、是非ともお願いします！

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW Cloud Functionsにテストで `setTimeLimit()` デプロイしてます！邪魔だったら消しちゃって 👍

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay ありがとう！明日の朝までにpushできたら明日はそのレビューから、間に合わなければ多分どこかで詰まってるので相談させて！

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay ごめん、Cloud Functionsって共有されてたっけ？？

**Comment by RQ2L84Q-ROW** [comment]
@yhakamay ごめんやっぱりよくわかんない！どこも押せないんだけど、これってもしかして編集権限ない？
<img width="1363" alt="Screen Shot 2021-09-15 at 22 27 44" src="https://user-images.githubusercontent.com/62736166/133441991-4cf93be1-3925-49ef-b010-7d86fb160d57.png">

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW わーごめん気づかなかった、明日話す！
