### ISSUE TITLE
タイマーのボタンを連打すると、isRunningとボタンの状態がズレる

### ISSUE THREAD

**Issue by yhakamay** [hummingbird-jp/stat-web#86]
これ、Firestoreとのやり取りにラグがあるから仕方ないのよねえ 🤔 ちょっと考えます

**Comment by yhakamay** [comment]
根治ではなく対症療法だけど、開始/停止ボタンを押したときに500msくらい `disabled: true` にしようかな

**Comment by RQ2L84Q-ROW** [comment]
対処両方的には、ボタンを押してから一定時間はボタンが無効になるようにする、とか。

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW そうね、その方法で対処します！コメントありがとう

**Comment by yhakamay** [comment]
なんかめっちゃ上手くいかないので明日やります 🙇‍♂️

**Comment by yhakamay** [comment]
うーん、ちょっと凝り固まっちゃってる感じするので一旦他のissue対応します

**Comment by RQ2L84Q-ROW** [comment]
もくもく会もあり

**Comment by yhakamay** [comment]
@RQ2L84Q-ROW ありがたい、今日夜お願いしても良いですか 🙇‍♂️
