### ISSUE TITLE
横棒が画面の外に出る

### ISSUE THREAD

**Issue by yhakamay** [hummingbird-jp/stat-web#94]
最大数はやっぱり変化させない方が良いかも 🤔  いける？
![image](https://user-images.githubusercontent.com/65002858/132487277-84843880-7f68-4016-a85f-cd970756ee9e.png)

**Comment by yhakamay** [comment]
ミーティング開始直後に文字が潰れる問題もあるから、やはり全体量は固定が良いかな… ここは議論しよう！
![image](https://user-images.githubusercontent.com/65002858/132491435-4acf3335-1ced-4c54-900e-d0ad9d0f3ec7.png)

**Comment by RQ2L84Q-ROW** [comment]
やっぱ潰れるの気になるよね
固定長に変更します！

人数が多くなるとそれでも潰れちゃうけど、そこは追い追い考えたい。

**Comment by RQ2L84Q-ROW** [comment]
枠がはみ出ちゃうのはすぐ直せます！
